### ISSUE TITLE
help

### ISSUE THREAD

**Issue by zakarianamikaz** [LiyuanLucasLiu/ArabicNER#2]
i don't know why it keep given me this error:
python3 train_ner.py --train_file train.txt
[2019-09-02 15:46:33,390] Checkpoint Folder Already Exists: ./checkpoint/sner0  
[2019-09-02 15:46:33,390] Input 'yes' to confirm deleting this folder; or 'no' to exit.
yes for delete or no for exit: yes
[2019-09-02 15:46:35,951] Saving system environemnt and python packages         
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
[2019-09-02 15:46:36,744] Loading the data...                                   
[2019-09-02 15:46:36,744] Building lm pipeline...                               
Traceback (most recent call last):
  File "train_ner.py", line 35, in <module>
    train_data = strFromFileEncoderWrapper(args, processed_file = conf.train_file)
  File "/home/zakaria/Downloads/ArabicNER/abnlp/encoder/str_encoder.py", line 301, in __init__
    super(strFromFileEncoderWrapper, self).__init__(arg)
  File "/home/zakaria/Downloads/ArabicNER/abnlp/encoder/str_encoder.py", line 35, in __init__
    self.build_pipelines(arg)
  File "/home/zakaria/Downloads/ArabicNER/abnlp/encoder/str_encoder.py", line 309, in build_pipelines
    self.pipeline_dict[key] = strFromFilePipeline(arg['strEncoder'][key], key)
  File "/home/zakaria/Downloads/ArabicNER/abnlp/encoder/str_encoder.py", line 252, in __init__
    super(strFromFilePipeline, self).__init__(arg)
  File "/home/zakaria/Downloads/ArabicNER/abnlp/encoder/str_encoder.py", line 66, in __init__
    self.build_pipeline(arg)
  File "/home/zakaria/Downloads/ArabicNER/abnlp/encoder/str_encoder.py", line 258, in build_pipeline
    self.instances = json.load(fin)[self.name]
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by LiyuanLucasLiu** [comment]
Hi thanks for asking :-)
the input format for `train_ner.py` should be a json file instead of a `.txt` file. 
you can follow the `train.sh` script to pre-process the `.txt` file and get the json file. (We would recommend to set up the docker container with the following command (after replacing `<Output Path>` with a path for generating output files).
```
nvidia-docker build -t arabic_ner .
nvidia-docker run -v ``pwd''/data:/data:ro -v <Output Path>:/wdata -it arabic_ner 
```

**Comment by zakarianamikaz** [comment]
thanks for you resp
can i work without docker ! because i d'ont know it seem not to work for me (versions problem)

**Comment by LiyuanLucasLiu** [comment]
You can also follow the [`dockefile`](https://github.com/LiyuanLucasLiu/ArabicNER/blob/master/dockerfile) to set up the environment. Also, you need to modify the `train.sh` script accordingly.

**Comment by zakarianamikaz** [comment]
yes i've followed the dockerfile and i had the embed folder, what i should modify in train.sh
