### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by zakarianamikaz** [LiyuanLucasLiu/ArabicNER#3]
python2 train_ner.py --train-file train.json
Traceback (most recent call last):
  File "train_ner.py", line 1, in <module>
    from torch_scope import wrapper
  File "/home/zakaria/anaconda3/lib/python2.7/site-packages/torch_scope/__init__.py", line 7, in <module>
    from torch_scope.wrapper import wrapper, basic_wrapper
  File "/home/zakaria/anaconda3/lib/python2.7/site-packages/torch_scope/wrapper.py", line 325
    path: str, 
        ^
SyntaxError: invalid syntax

**Comment by LiyuanLucasLiu** [comment]
please try python 3.6 / 3.7
