### ISSUE TITLE
bash train not working

### ISSUE THREAD

**Issue by zakarianamikaz** [LiyuanLucasLiu/ArabicNER#4]
it this normal and in ./data i have my train.txt fil in arabic 
bash train.sh ./data
=== Removing Pre-trained Models ===
=== Cleaning Data ===
Traceback (most recent call last):
  File "data_clean/data_clean.py", line 68, in <module>
    with codecs.open(args.train_file_output, 'w', 'utf-8') as fout:
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/codecs.py", line 904, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/wdata/train_cleaned.txt'
=== Building Dictionary Based Model ===
Traceback (most recent call last):
  File "post_process/save_dictionary.py", line 45, in <module>
    with open(args.dict_output, 'w') as fout:
FileNotFoundError: [Errno 2] No such file or directory: '/wdata/train_dict.json'
=== Data Pre-processing ===
Traceback (most recent call last):
  File "pre_process_train.py", line 21, in <module>
    encoder = strRealTimeEncoderWrapper(args)
  File "/home/zakaria/Downloads/ArabicNER/abnlp/encoder/str_encoder.py", line 35, in __init__
    self.build_pipelines(arg)
  File "/home/zakaria/Downloads/ArabicNER/abnlp/encoder/str_encoder.py", line 281, in build_pipelines
    self.pipeline_dict[key] = strWERealTimePipeline(arg['strEncoder'][key])
  File "/home/zakaria/Downloads/ArabicNER/abnlp/encoder/str_encoder.py", line 66, in __init__
    self.build_pipeline(arg)
  File "/home/zakaria/Downloads/ArabicNER/abnlp/encoder/str_encoder.py", line 159, in build_pipeline
    for line in f.readlines():
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/codecs.py", line 709, in readlines
    return self.reader.readlines(sizehint)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/codecs.py", line 618, in readlines
    data = self.read()
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/codecs.py", line 496, in read
    newdata = self.stream.read()
MemoryError
=== Training Model 0 ===
Traceback (most recent call last):
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 40, in directory_check
    factory = REGISTERED_FACTORIES[prefix]
KeyError: '/wdata/sner0/log/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_ner.py", line 32, in <module>
    pw = wrapper(os.path.join(conf.cp_root, args["checkpoint_name"]), args["checkpoint_name"])
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/torch_scope/wrapper.py", line 361, in __init__
    self.writer = SummaryWriter(log_dir=os.path.join(path, 'log/'))
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 257, in __init__
    self._get_file_writer()
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 321, in _get_file_writer
    **self.kwargs)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 93, in __init__
    logdir, max_queue, flush_secs, filename_suffix)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/event_file_writer.py", line 104, in __init__
    directory_check(self._logdir)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 44, in directory_check
    os.makedirs(path)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/wdata'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

=== Training Model 1 ===
Traceback (most recent call last):
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 40, in directory_check
    factory = REGISTERED_FACTORIES[prefix]
KeyError: '/wdata/sner1/log/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_ner.py", line 32, in <module>
    pw = wrapper(os.path.join(conf.cp_root, args["checkpoint_name"]), args["checkpoint_name"])
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/torch_scope/wrapper.py", line 361, in __init__
    self.writer = SummaryWriter(log_dir=os.path.join(path, 'log/'))
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 257, in __init__
    self._get_file_writer()
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 321, in _get_file_writer
    **self.kwargs)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 93, in __init__
    logdir, max_queue, flush_secs, filename_suffix)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/event_file_writer.py", line 104, in __init__
    directory_check(self._logdir)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 44, in directory_check
    os.makedirs(path)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/wdata'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

=== Training Model 2 ===
Traceback (most recent call last):
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 40, in directory_check
    factory = REGISTERED_FACTORIES[prefix]
KeyError: '/wdata/sner2/log/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_ner.py", line 32, in <module>
    pw = wrapper(os.path.join(conf.cp_root, args["checkpoint_name"]), args["checkpoint_name"])
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/torch_scope/wrapper.py", line 361, in __init__
    self.writer = SummaryWriter(log_dir=os.path.join(path, 'log/'))
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 257, in __init__
    self._get_file_writer()
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 321, in _get_file_writer
    **self.kwargs)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 93, in __init__
    logdir, max_queue, flush_secs, filename_suffix)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/event_file_writer.py", line 104, in __init__
    directory_check(self._logdir)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 44, in directory_check
    os.makedirs(path)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/wdata'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

=== Training Model 3 ===
Traceback (most recent call last):
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 40, in directory_check
    factory = REGISTERED_FACTORIES[prefix]
KeyError: '/wdata/sner3/log/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_ner.py", line 32, in <module>
    pw = wrapper(os.path.join(conf.cp_root, args["checkpoint_name"]), args["checkpoint_name"])
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/torch_scope/wrapper.py", line 361, in __init__
    self.writer = SummaryWriter(log_dir=os.path.join(path, 'log/'))
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 257, in __init__
    self._get_file_writer()
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 321, in _get_file_writer
    **self.kwargs)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 93, in __init__
    logdir, max_queue, flush_secs, filename_suffix)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/event_file_writer.py", line 104, in __init__
    directory_check(self._logdir)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 44, in directory_check
    os.makedirs(path)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/wdata'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

=== Training Model 4 ===
Traceback (most recent call last):
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 40, in directory_check
    factory = REGISTERED_FACTORIES[prefix]
KeyError: '/wdata/sner4/log/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_ner.py", line 32, in <module>
    pw = wrapper(os.path.join(conf.cp_root, args["checkpoint_name"]), args["checkpoint_name"])
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/torch_scope/wrapper.py", line 361, in __init__
    self.writer = SummaryWriter(log_dir=os.path.join(path, 'log/'))
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 257, in __init__
    self._get_file_writer()
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 321, in _get_file_writer
    **self.kwargs)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 93, in __init__
    logdir, max_queue, flush_secs, filename_suffix)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/event_file_writer.py", line 104, in __init__
    directory_check(self._logdir)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 44, in directory_check
    os.makedirs(path)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/wdata'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

=== Training Model 5 ===
Traceback (most recent call last):
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 40, in directory_check
    factory = REGISTERED_FACTORIES[prefix]
KeyError: '/wdata/sner5/log/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_ner.py", line 32, in <module>
    pw = wrapper(os.path.join(conf.cp_root, args["checkpoint_name"]), args["checkpoint_name"])
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/torch_scope/wrapper.py", line 361, in __init__
    self.writer = SummaryWriter(log_dir=os.path.join(path, 'log/'))
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 257, in __init__
    self._get_file_writer()
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 321, in _get_file_writer
    **self.kwargs)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 93, in __init__
    logdir, max_queue, flush_secs, filename_suffix)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/event_file_writer.py", line 104, in __init__
    directory_check(self._logdir)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 44, in directory_check
    os.makedirs(path)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/wdata'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

=== Training Model 6 ===
Traceback (most recent call last):
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 40, in directory_check
    factory = REGISTERED_FACTORIES[prefix]
KeyError: '/wdata/sner6/log/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_ner.py", line 32, in <module>
    pw = wrapper(os.path.join(conf.cp_root, args["checkpoint_name"]), args["checkpoint_name"])
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/torch_scope/wrapper.py", line 361, in __init__
    self.writer = SummaryWriter(log_dir=os.path.join(path, 'log/'))
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 257, in __init__
    self._get_file_writer()
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 321, in _get_file_writer
    **self.kwargs)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 93, in __init__
    logdir, max_queue, flush_secs, filename_suffix)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/event_file_writer.py", line 104, in __init__
    directory_check(self._logdir)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 44, in directory_check
    os.makedirs(path)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/wdata'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

=== Training Model 7 ===
Traceback (most recent call last):
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 40, in directory_check
    factory = REGISTERED_FACTORIES[prefix]
KeyError: '/wdata/sner7/log/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_ner.py", line 32, in <module>
    pw = wrapper(os.path.join(conf.cp_root, args["checkpoint_name"]), args["checkpoint_name"])
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/torch_scope/wrapper.py", line 361, in __init__
    self.writer = SummaryWriter(log_dir=os.path.join(path, 'log/'))
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 257, in __init__
    self._get_file_writer()
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 321, in _get_file_writer
    **self.kwargs)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 93, in __init__
    logdir, max_queue, flush_secs, filename_suffix)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/event_file_writer.py", line 104, in __init__
    directory_check(self._logdir)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 44, in directory_check
    os.makedirs(path)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/wdata'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

=== Training Model 8 ===
Traceback (most recent call last):
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 40, in directory_check
    factory = REGISTERED_FACTORIES[prefix]
KeyError: '/wdata/sner8/log/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_ner.py", line 32, in <module>
    pw = wrapper(os.path.join(conf.cp_root, args["checkpoint_name"]), args["checkpoint_name"])
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/torch_scope/wrapper.py", line 361, in __init__
    self.writer = SummaryWriter(log_dir=os.path.join(path, 'log/'))
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 257, in __init__
    self._get_file_writer()
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 321, in _get_file_writer
    **self.kwargs)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/writer.py", line 93, in __init__
    logdir, max_queue, flush_secs, filename_suffix)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/event_file_writer.py", line 104, in __init__
    directory_check(self._logdir)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/site-packages/tensorboardX/record_writer.py", line 44, in directory_check
    os.makedirs(path)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/zakaria/anaconda3/envs/py37/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/wdata'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by LiyuanLucasLiu** [comment]
you need to set the path correctly. mainly `/data', and '/wdata'

**Comment by zakarianamikaz** [comment]
wish version of torch
